language: node_js
node_js:
  - "node"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: build

on:
  branch: master
